---
- name: Prepare Kubernetes Nodes
  hosts: kube_cluster
  become: yes
  tasks:

    - name: Disable Swap
      command: swapoff -a
      when: ansible_virtualization_type != "docker"

    - name: Remove swap entry from /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '.*swap.*'
        replace: ''

    - name: Load Kernel Modules Configuration
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load Kernel Modules Immediately
      shell: |
        modprobe overlay
        modprobe br_netfilter

    - name: Set Kernel Parameters for Kubernetes
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl params without reboot
      command: sysctl --system

    - name: Add Kubernetes nodes to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
      with_items:
        - "192.168.100.200 master01"   #replace this line with your VMs ip and hostname
        - "192.168.100.201 node01"
        - "192.168.100.202 node02"
